FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    python3-pip \
    python3-flask \
    python3-gunicorn \
    python3-redis \
    jq --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY \
{% for deb in docker_sonic_yang_utils_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_sonic_yang_utils_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

COPY ["start.sh", "yang-utils.sh", "/usr/bin/"]
COPY ["yang_utils_vars.j2", "/usr/share/sonic/templates/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

RUN chmod +x /usr/bin/start.sh
RUN chmod +x /usr/bin/yang-utils.sh

EXPOSE 5000

ENTRYPOINT ["/usr/local/bin/supervisord"]
