{% from "dockers/dockerfile-macros.j2" import install_debian_packages, copy_files %}
ARG BASE=docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE 

ARG docker_container_name

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive
# RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

RUN apt-get update 
RUN apt-get install -y \
    python3-pip \
    python3-flask \
    python3-gunicorn \
    python3-redis \
    jq --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN apt-get -y install libjemalloc1 libatomic1 liblua5.1-0 lua-bitop lua-cjson

{% if docker_sonic_yang_utils_debs.strip() -%}
# Copy built Debian packages
{{ copy_files("debs/", docker_sonic_yang_utils_debs.split(' '), "/debs/") }}

# Install built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_sonic_yang_utils_debs.split(' ')) }}
{%- endif %}

COPY ["start.sh", "yang-utils.sh", "/usr/bin/"]
COPY ["yang_utils_vars.j2", "/usr/share/sonic/templates/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

RUN chmod +x /usr/bin/start.sh
RUN chmod +x /usr/bin/yang-utils.sh

RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

EXPOSE 5000

ENTRYPOINT ["/usr/local/bin/supervisord"]
