# docker image for yang-utils

DOCKER_YANG_UTILS_STEM = docker-sonic-yang-utils
DOCKER_YANG_UTILS = $(DOCKER_YANG_UTILS_STEM).gz

$(DOCKER_YANG_UTILS)_PATH = $(DOCKERS_PATH)/$(DOCKER_YANG_UTILS_STEM)

$(DOCKER_YANG_UTILS)_DEPENDS += $(SONIC_YANG_UTILS)

SONIC_DOCKER_IMAGES += $(DOCKER_YANG_UTILS)
$(DOCKER_YANG_UTILS)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_YANG_UTILS)_VERSION = 1.0.0
$(DOCKER_YANG_UTILS)_PACKAGE_NAME = yang-utils

ifeq ($(INCLUDE_YANG_UTILS), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_YANG_UTILS)
endif

$(DOCKER_YANG_UTILS)_CONTAINER_NAME = yang-utils
$(DOCKER_YANG_UTILS)_RUN_OPT += --privileged -t
$(DOCKER_YANG_UTILS)_RUN_OPT += -v /etc/sonic:/etc/sonic:rw
$(DOCKER_YANG_UTILS)_RUN_OPT += -v /etc:/host_etc:ro
$(DOCKER_YANG_UTILS)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw
$(DOCKER_YANG_UTILS)_RUN_OPT += --mount type=bind,source="/var/platform/",target="/mnt/platform/"

SONIC_BOOKWORM_DOCKERS += $(DOCKER_YANG_UTILS) 
