# SONiC yang-utils package

ifeq ($(INCLUDE_YANG_UTILS), y)

SONIC_YANG_UTILS = sonic-yang-utils_1.0-01_$(CONFIGURED_ARCH).deb
$(SONIC_YANG_UTILS)_SRC_PATH = $(SRC_PATH)/sonic-yang-utils
$(SONIC_YANG_UTILS)_DEPENDS  = 
$(SONIC_YANG_UTILS)_RDEPENDS = 
SONIC_DPKG_DEBS += $(SONIC_YANG_UTILS)

endif